# Numpy Workbook
Workbook to get learn and get used to NumPy

## Numpy Basics
Some numpy basics to get stared

### 1. To import NumPy


In [11]:
import numpy as np
np.__version__

'1.18.5'

### 2. To display all the contents of NumPy namespace & to check built-in documentaion

press tab after "." --> np."tab"<br><br>
np?

 



### 3. Creating Arrays

In [14]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [16]:
#upcast
np.array([1.0,2,3,4,5]) 

array([1., 2., 3., 4., 5.])

In [18]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [23]:
#multidimensional array using list of lists
np.array([range(i, i+8) for i in [2,4,6]]) 

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10, 11],
       [ 6,  7,  8,  9, 10, 11, 12, 13]])

### 4. Creating Arrays from scratch

In [25]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
#Create a 6x3 floating-point array filled with 1s
np.ones((6,3), dtype='float')

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
# Create a 7x2 array filled with x
x=3.14
np.full((7,2),x)

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

In [43]:
# Create an array filled with a linear sequence
print(np.arange(2,20,2))

#similar 
np.array([int(i) for i in range (2,20,2)])
    

[ 2  4  6  8 10 12 14 16 18]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [49]:
#  Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [51]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1

np.random.random((3,3))

array([[0.89945312, 0.16425456, 0.0275315 ],
       [0.2230939 , 0.75248412, 0.82473605],
       [0.01537161, 0.73705487, 0.02937098]])

In [52]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.10275625,  0.31852535, -0.32010169],
       [-1.03408889, -0.2825916 ,  0.87949865],
       [-0.89852987, -1.15049306,  0.05810469]])

In [53]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[4, 0, 2],
       [8, 5, 8],
       [1, 6, 4]])

In [54]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Create an uninitialized array of three integers
#### The values will be whatever happens to already exist at that  Standard NumPy data types
Data type          Description <br>
bool_              &emsp;&emsp;&emsp;&emsp;&emsp;Boolean (True or False) stored as a byte <br>
int_               &emsp;&emsp;&emsp;&emsp;&emsp;&ensp;&nbsp;Default integer type (same as C long; normally either int64 or int32) <br>
intc               &emsp;&emsp;&emsp;&emsp;&emsp;&ensp;&nbsp;Identical to C int (normally int32 or int64) <br>
intp               &emsp;&emsp;&emsp;&emsp;&emsp;&ensp;Integer used for indexing (same as C ssize_t; normally either int32 or int64) <br>
int8               &emsp;&emsp;&emsp;&emsp;&emsp;&ensp;Byte (–128 to 127) <br>
int16              &emsp;&emsp;&emsp;&emsp;&emsp;Integer (–32768 to 32767) <br>
int32              &emsp;&emsp;&emsp;&emsp;&emsp;Integer (–2147483648 to 2147483647) <br>
int64              &emsp;&emsp;&emsp;&emsp;&emsp;Integer (–9223372036854775808 to 9223372036854775807) <br>
uint8              &emsp;&emsp;&emsp;&emsp;&emsp;Unsigned integer (0 to 255) <br>
uint16             &emsp;&emsp;&emsp;&emsp;&ensp;Unsigned integer (0 to 65535) <br>
uint32             &emsp;&emsp;&emsp;&emsp;&ensp;Unsigned integer (0 to 4294967295) <br>
uint64             &emsp;&emsp;&emsp;&emsp;&ensp;Unsigned integer (0 to 18446744073709551615) <br>
float_             &emsp;&emsp;&emsp;&emsp;&emsp;Shorthand for float64 <br>
float16            &emsp;&emsp;&emsp;&emsp;&nbsp;Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa <br>
float32            &emsp;&emsp;&emsp;&emsp;&nbsp;Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa <br>
float64            &emsp;&emsp;&emsp;&emsp;&nbsp;Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa <br>
complex_           &emsp;&emsp;&emsp;&nbsp;Shorthand for complex128 <br>
complex64          &emsp;&emsp;&ensp;Complex number, represented by two 32-bit floats <br>
complex128         &emsp;&emsp;Complex number, represented by two 64-bit floatsmemory location <br>

## 4. NumPy Array attributes

In [57]:
#  seed for reproducibility
np.random.seed(0)


In [63]:
# arrays with elemnts between 0-10
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array


#### 1. x.dim - To check dimensions 
#### 2. x.shape - To check shape 
#### 3. x.size - To check size 

In [78]:
print(x1)
print("Dimensions - ",x1.ndim)
print("Shape - ",x1.shape)
print("Size - ",x1.size)

[8 5 4 7 4 1]
Dimensions -  1
Shape -  (6,)
Size -  6


In [79]:
print(x2)
print("Dimensions - ",x2.ndim)
print("Shape - ",x2.shape)
print("Size - ",x2.size)

[[3 3 9 2]
 [5 2 3 5]
 [7 2 7 1]]
Dimensions -  2
Shape -  (3, 4)
Size -  12


In [76]:
print(x3)
print("Dimensions - ",x3.ndim)
print("Shape - ",x3.shape)
print("",x3.size)

[[[6 5 0 0 3]
  [1 9 9 6 6]
  [7 8 8 7 0]
  [8 6 8 9 8]]

 [[3 6 1 7 4]
  [9 2 0 8 2]
  [7 8 4 4 1]
  [7 6 9 4 1]]

 [[5 9 7 1 3]
  [5 7 3 6 6]
  [7 9 1 9 6]
  [0 3 8 4 1]]]
Dimensions -  3
Shape -  (3, 4, 5)
Size -  60
